version: '2.2'
services:
  demo-web:
    build: ./3rd_party_demo
    container_name: demo_web
  acc-service:
    build: ./account-service
    container_name: account_service
    depends_on:
      acc-db:
        condition: service_healthy
    links:
     - acc-db
    environment:
    # - NODE_ENV=production
    # - HOSTNAME=gisid.cdg.co.th
    # - WEB_DOMAIN=gisid.cdg.co.th
     - NODE_ENV=test
     - HOSTNAME=dev.cdg.co.th
     - WEB_DOMAIN=dev.cdg.co.th
     - DB_HOSTNAME=acc-db
     - DB_PORT=5432
     - SMPT_HOST=mailgateway.cdg.co.th
    extra_hosts:
     - "mailgateway.cdg.co.th:10.254.7.51"
    volumes:
     - acc-images-data:/usr/src/app/upload
    healthcheck:
      test: curl -I -s -L http://127.0.0.1:3000/g/check/version
      interval: 10s
      timeout: 5s
      retries: 5
  acc-db:
    build: ./account-db
    container_name: "acc-postgres-db"
    restart: always
    volumes:
      - acc-db-data:/var/lib/postgresql/data
    ports:
      - 5455:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  kong-database:
    build: ./kong-db
    container_name: kong_database
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - kong-db-data:/var/lib/postgresql/data
  kong-gateway:
    build: ./kong
    container_name: kong_gateway
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kongmin
      - KONG_PG_PASSWORD=27gJ2zpYw9GQgndH
      - KONG_PG_PORT=5432
    command: sh -c 'kong migrations up  && kong start'
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
  nginx:
    build: ./reverse-proxy
    container_name: "rev_proxy"
    links:
     - acc-service
     - demo-web
    ports:
      - 80:80
      - 443:443
    extra_hosts:
     - "dev.cdg.co.th:10.0.75.1" ## for Dev local only
     - "gisid.cdg.co.th:10.254.7.23"
volumes:
  acc-db-data:
  kong-db-data:
  acc-images-data: