version: '2.2'
services:
  acc-service:
    build: ./account-service
    container_name: account_service
    command: sh -c './wait-for acc-db:5432 -- npm start'
    depends_on:
     - acc-db
    links:
     - acc-db
    environment:
     - NODE_ENV=production
     - DB_HOSTNAME=acc-db
     - DB_PORT=5432
     - HOSTNAME=gisid.cdg.co.th
     - SMPT_HOST=mailgateway.cdg.co.th
     - http_proxy http://10.254.7.89:8080
     - https_proxy http://10.254.7.89:8080
  acc-db:
    build: ./account-db
    container_name: "acc-postgres-db"
    restart: always
    volumes:
      - acc-db-data:/var/lib/postgresql/data
    ports:
      - 5455:5432
  nginx:
    build: ./reverse-proxy
    container_name: "rev_proxy"
    links:
     - acc-service
    ports:
      - 81:80
volumes:
  acc-db-data: