version: '2.2'
services:
  kong-database:
    image: postgres:9.4-alpine
    container_name: kong_database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - kong-db-data:/var/lib/postgresql/data
  kong-migration:
    image: kong:0.11-alpine
    container_name: kong_migration
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up
  acc-service:
    build: ./account-service
    container_name: account_service
    #command: sh -c './wait-for acc-db:5432 -- npm start'
    depends_on:
      acc-db:
        condition: service_healthy
    links:
     - acc-db
    environment:
    # - NODE_ENV=production
    # - HOSTNAME=gisid.cdg.co.th
    # - WEB_DOMAIN=gisid.cdg.co.th
     - NODE_ENV=test
     - HOSTNAME=dev.cdg.co.th
     - WEB_DOMAIN=dev.cdg.co.th
     - DB_HOSTNAME=acc-db
     - DB_PORT=5432
     - SMPT_HOST=mailgateway.cdg.co.th
    extra_hosts:
     - "mailgateway.cdg.co.th:10.254.7.51"
    volumes:
     - acc-images-data:/usr/src/app/upload
    healthcheck:
      test: curl -I -s -L http://127.0.0.1:3000/g/check/version
      interval: 10s
      timeout: 5s
      retries: 5
  acc-db:
    build: ./account-db
    container_name: "acc-postgres-db"
    restart: always
    volumes:
      - acc-db-data:/var/lib/postgresql/data
    ports:
      - 5455:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  kong-gateway:
    build: ./kong
    container_name: kong_gateway
    depends_on:
      kong-database:
        condition: service_healthy
      acc-service:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
  #kongfig:
  #  build: ./kongfig
  #  container_name: kongfiger
  #  links:
  #   - kong-gateway
  nginx:
    build: ./reverse-proxy
    container_name: "rev_proxy"
    links:
     - acc-service
    ports:
      - 80:80
      - 443:443
    extra_hosts:
     - "dev.cdg.co.th:10.0.75.1" ## for Dev local only
     - "gisid.cdg.co.th:10.254.7.23"
volumes:
  acc-db-data:
  kong-db-data:
  acc-images-data: