version: '2.2'
services:
  acc-service:
    build: ./account-service
    container_name: account_service
    ports:
     - "3010:3001"
    command: sh -c './wait-for acc-db:5432 -- npm start'
    depends_on:
     - acc-db
    links:
     - acc-db
    environment:
     - DB_HOSTNAME=acc-db
     - DB_PORT=5432
  acc-db:
    build: ./account-db
    container_name: "acc-postgres-db"
    restart: always
    volumes:
      - acc-db-data:/var/lib/postgresql/data
    ports:
      - 5455:5432
volumes:
  acc-db-data: